#ifndef _HQ_INTERFACES_H_
#define _HQ_INTERFACES_H_

#define INTERFACE_TYPE_DPDK 4
#define INTERFACE_TYPE_MODEL 10
#define INTERFACE_TYPE_MODEL_SIM 11
#define INTERFACE_TYPE_NONE 6
#define INTERFACE_TYPE_OPAE 3
#define INTERFACE_TYPE_PAGES 8
#define INTERFACE_TYPE_POSIX_FIFO 2
#define INTERFACE_TYPE_POSIX_MQ 1
#define INTERFACE_TYPE_POSIX_SHM 5
#define INTERFACE_TYPE_SOCKETS_UNIX 9
#define INTERFACE_TYPE_ZERO 7

#endif /* _HQ_INTERFACES_H_ */
